### ISSUE TITLE
File Format Enhancements

### ISSUE THREAD

**Issue by leondroidgeeks** [kewisch/sepa.js#34] opened 2019-07-05 19:52 UTC
Two problems I had and how I solved them:

First from online banking I got an error that my file is not valid. That was due to the fact that my file contained IBANs with spaces: "XXXX XXXX XXXX .... ". So I just had to remove the spaces with 

`tx.debtorIBAN = transaction.debtorIBAN.replace(/\s+/g, '');`

Second the generated file that was generated with 

```
var blob = new Blob([doc.toString], { type: "text/xml;charset=utf-8" });
saveAs(blob, "sepa.xml");
```

wasn't recognized as XML either by my computer nor by the online banking. I fixed this by first generating an XML object from the sepa.js object and serializing this object to String by using the XMLSerializer:

```
var oSerializer = new XMLSerializer();
var blob = new Blob([oSerializer.serializeToString(doc.toXML())], { type: "text/xml;charset=utf-8" });
saveAs(blob, "sepa.xml");
```

Maybe this package can be enhanced by incorporating this fixes.

**Comment by jacobo221** [comment] 2020-05-28 17:41
The problem is with xmlEnconding, its been deprecated since 2011 and Chrome a year ago made it a readonly attribute set to null, which makes bank processors fail to understand the encoding.

References:
https://bugzilla.mozilla.org/show_bug.cgi?id=687426
https://bugs.chromium.org/p/chromium/issues/detail?id=683827

Serializing the xml and then appending the xml header seems the right  way to get the SEPA string right now. So, instead of:

var sepaDoc = new SEPA.Document();
...
var sepaSting= sepaDoc.toString();

you must write:

var sepaDoc = new SEPA.Document();
...
var sepaString = "<"+"?xml version=\"1.0\" encoding=\"UTF-8\">"+(new XMLSerializer()).serializeToString(sepaDoc.toXML());

The "<"+"?xml ... form is just in case you are using this code in a PHP file.

**Comment by kewisch** [comment] 2022-06-10 10:56
What would be a good way to fix these issues? Would you be willing to look into creating a PR?

**Comment by lippertto** [comment] 2023-11-29 06:51
From what I see, the behavior of `toString()` now creates a valid xml declaration. I have added a test for this behavior in the PR. I would suggest to close this ticket.

**Comment by kewisch** [comment] 2023-11-29 11:44
Thanks for verifying!

**Closed by kewisch** 2023-11-29 11:44 UTC
Labels: bug
